### PR TITLE
Standardized OpenAI config format and updated documentation issue #1180

### LINKED ISSUE #1180: [doc] configuring AI services
We need documentation to supplement the [existing config documentation](https://github.com/HeyPuter/puter/wiki/self_hosters-config) that specifically explains how to configure AI services. This documentation probably belongs under `src/backend/src/modules/puterai/doc` but should be linked to from the general config documentation.

Every AI service, with the exception of `openai`, currently adheres to this format in configuration:

```json
  "services": {
    "<name-of-ai-service>": {
      "apiKey": "sk-abcdefg..."
    }
  }
```

For `openai` specifically, right now it doesn't go in the `services` block and uses a different name for the key:
```json
  "openai": {
    "secret_key": "sk-abcdefg..."
  }
```

So the following should be done:
- make OpenAI config consistent, but also make this backward-compatible
- document how keys are configured for AI services
- (we do not need to document the legacy config behavior for OpenAI)

### PR DESCRIPTION
**Pull request by anuja12mishra**
## Description
This PR addresses the issue of inconsistent AI service configuration by:
1. Making OpenAI configuration consistent with other AI services.
2. Adding documentation for configuring AI services.
3. Ensuring backward compatibility for the legacy OpenAI configuration format.

## Changes
- Updated OpenAI configuration to use the `services` block and `apiKey`.
- Added new documentation under `src/backend/src/modules/puterai/doc/ai-services-config.md`.
- Linked the new documentation from the general configuration docs.

## Related Issue
Fixes #1180

### CODE REVIEW

File: src/backend/src/modules/puterai/OpenAICompletionService.js [hunk 1]
```diff
@@ -52,15 +52,53 @@ class OpenAICompletionService extends BaseService {
...
+    //         apiKey: sk_key
+    //     });
+
+    //     const svc_aiChat = this.services.get('ai-chat');
+    //     svc_aiChat.register_provider({
+    //         service_name: this.service_name,
+    //         alias: true,
+    //     });
+    // }
+
```
Comment (KernelDeimos) [inline src/backend/src/modules/puterai/OpenAICompletionService.js]: Since we use git, we can just remove old code instead of commenting it out.

```suggestion
```

File: src/backend/src/modules/puterai/doc/ai-services-config.md [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+AI services are configured under the `services` block in the configuration file. Each service requires an `apiKey` to authenticate requests.
+
+## Example Configuration
+```json
+{
+  "services": {
+    "openai": {
+      "apiKey": "sk-abcdefg..."
+    },
+    "other-ai-service": {
```
Comment (KernelDeimos) [inline src/backend/src/modules/puterai/doc/ai-services-config.md:15]: Maybe we should list what other services are available as well

**Review by KernelDeimos — COMMENTED** [review]
Looks good, just two minor comments - I'll merge in 24 hours whether these are addressed or not.

**Comment by anuja12mishra** [comment]
@KernelDeimos Sir, I've added an example list of available AI services in the documentation (ai-services-config.md) and removed the comment in OpenAICompletionService.js. Let me know if any further changes are needed!

**Comment by KernelDeimos** [comment]
Merged, thanks!
