### PR TITLE
fixing issues in copy while overwriting

### LINKED ISSUE #80: Api call for copy with overwrite set to true is failing with 500
### Steps to reproduce
Copy a file to a directory which already has a file with the same name

Screenshot 2024-03-12 at 9 46 33 AM

### PR DESCRIPTION
**Pull request by vineeth-vk11**
This PR closes #80 

options.user.id was causing the issue since there is no variable named options, has to change it to values

The other changes are related to handling the removal of overwritten item from DOM on the frontend.

Followed a similar approach to move operation, returned the overwritten item id in the api response and removed the item with that uid from DOM.

### CODE REVIEW

File: packages/backend/src/filesystem/hl_operations/hl_copy.js [hunk 1]
```diff
@@ -189,12 +190,13 @@ class HLCopy extends HLFilesystemOperation {
                 dest = await parent.getChild(target_name);
             }
             else if ( values.overwrite ) {
-                if ( ! await chkperm(dest.entry, options.user.id, 'rm') ) {
+                if ( ! await chkperm(dest.entry, values.user.id, 'rm') ) {
```
Comment (KernelDeimos) [inline packages/backend/src/filesystem/hl_operations/hl_copy.js:193]: yep

File: packages/backend/src/filesystem/hl_operations/hl_copy.js [hunk 2]
```diff
@@ -189,12 +190,13 @@ class HLCopy extends HLFilesystemOperation {
...
                     throw APIError.create('forbidden');
                 }
 
                 // TODO: This will be LLRemove
                 // TODO: what to do with parent_operation?
+                overwritten = await dest.getSafeEntry();
```
Comment (KernelDeimos) [inline packages/backend/src/filesystem/hl_operations/hl_copy.js:199]: definitely

File: packages/backend/src/filesystem/hl_operations/hl_copy.js [hunk 3]
```diff
@@ -213,7 +215,10 @@ class HLCopy extends HLFilesystemOperation {
 
         await this.copied.awaitStableEntry();
         const response = await this.copied.getSafeEntry({ thumbnail: true });
-        return response;
+        return {
+            copied : response,
+            overwritten
```
Comment (KernelDeimos) [inline packages/backend/src/filesystem/hl_operations/hl_copy.js:220]: oh right 😅

**Review by KernelDeimos — APPROVED** [review]
